server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE # Load balancer, 유레카 서버에서 찾음
          predicates:
            - Path=/user-service/**
        - id: catalog-service
          uri: lb://CATALOG-SERVICE # Load balancer, 유레카 서버에서 찾음
          predicates:
            - Path=/catalog-service/**
        - id: order-service
          uri: lb://ORDER-SERVICE # Load balancer, 유레카 서버에서 찾음
          predicates:
            - Path=/order-service/**
#      default-filters: # Global filter
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true
#        - id: second-service
#          uri: lb://SECOND-SERVICE # 유레카 서버에서 찾음
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: LoggingFilter
#                preLogger: true
#                postLogger: true
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
#            - CustomFilter